# Generated by Django 4.2 on 2023-07-07 12:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_summernote.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=1000)),
                ('name', models.CharField(max_length=500)),
                ('city_details', django_summernote.fields.SummernoteTextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10)),
                ('slug', models.CharField(max_length=1000, unique=True)),
                ('price', models.FloatField()),
                ('description', django_summernote.fields.SummernoteTextField(blank=True)),
                ('project_address', models.CharField(max_length=500)),
                ('postalcode', models.CharField(max_length=200)),
                ('latitute', models.CharField(max_length=10)),
                ('longitude', models.CharField(max_length=10)),
                ('date_of_upload', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('authour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authour_by', to=settings.AUTH_USER_MODEL)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listing.city')),
            ],
            options={
                'ordering': ('-updated_date',),
            },
        ),
        migrations.CreateModel(
            name='ListingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_type', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='ListingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='')),
                ('image_alt', models.CharField(default='image alt tag', max_length=500)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='listing.listing')),
            ],
        ),
        migrations.AddField(
            model_name='listing',
            name='type_of_listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_of_listing', to='listing.listingtype'),
        ),
    ]
