# Generated by Django 4.2 on 2023-07-15 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0003_remove_listing_postalcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='status',
        ),
        migrations.AddField(
            model_name='listing',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
