# Generated by Django 4.2 on 2023-07-15 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0005_alter_listing_title_alter_listingtype_listing_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='latitute',
            new_name='latitude',
        ),
    ]
