# Generated by Django 4.2 on 2023-07-18 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0006_rename_latitute_listing_latitude'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listing',
            options={'ordering': ('-updated_at',)},
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='date_of_upload',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='updated_date',
            new_name='updated_at',
        ),
    ]
