# Generated by Django 4.2 on 2023-07-18 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0007_alter_listing_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listingimage',
            name='image_alt',
        ),
    ]
