# Generated by Django 4.2 on 2023-07-20 12:34

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0009_remove_listing_latitude_remove_listing_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingtype',
            name='details',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
