# Generated by Django 4.2 on 2023-07-20 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0010_listingtype_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='square_footage',
            field=models.FloatField(default=0),
        ),
    ]
