# Generated by Django 4.2 on 2023-07-21 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0011_listing_square_footage'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='additional_data',
            field=models.JSONField(default=dict),
        ),
    ]
