# Generated by Django 4.2 on 2023-07-21 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0012_listing_additional_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='acerage',
            field=models.FloatField(default=0),
        ),
    ]
