# Generated by Django 4.2 on 2023-07-21 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0014_listingtype_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingtype',
            name='short_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='listingtype',
            name='thumbnail_image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
