# Generated by Django 4.2 on 2023-08-23 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0015_listingtype_short_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
