# Generated by Django 4.2 on 2023-07-07 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='thumbnail_image_alt_description',
        ),
    ]
